export {
  SYNTHETIC_DEFAULT_MODEL_ID,
  SYNTHETIC_DEFAULT_MODEL_REF,
} from "../agents/synthetic-models.js";
export { VENICE_DEFAULT_MODEL_ID, VENICE_DEFAULT_MODEL_REF } from "../agents/venice-models.js";
export {
  applyAuthProfileConfig,
  applyCloudflareAiGatewayConfig,
  applyCloudflareAiGatewayProviderConfig,
  applyKimiCodeConfig,
  applyKimiCodeProviderConfig,
  applyMoonshotConfig,
  applyMoonshotConfigCn,
  applyMoonshotProviderConfig,
  applyMoonshotProviderConfigCn,
  applyOpenrouterConfig,
  applyOpenrouterProviderConfig,
  applySyntheticConfig,
  applySyntheticProviderConfig,
  applyVeniceConfig,
  applyVeniceProviderConfig,
  applyVercelAiGatewayConfig,
  applyVercelAiGatewayProviderConfig,
  applyXiaomiConfig,
  applyXiaomiProviderConfig,
  applyZaiConfig,
  // 国内模型配置
  applyDeepseekConfig,
  applyDeepseekProviderConfig,
  applyBaiduQianfanConfig,
  applyBaiduQianfanProviderConfig,
  applyDoubaoConfig,
  applyDoubaoProviderConfig,
  applyTencentHunyuanConfig,
  applyTencentHunyuanProviderConfig,
  applyXinghuoConfig,
  applyXinghuoProviderConfig,
  applySiliconflowConfig,
  applySiliconflowProviderConfig,
  applyGroqConfig,
  applyGroqProviderConfig,
  applyTogetherAiConfig,
  applyTogetherAiProviderConfig,
} from "./onboard-auth.config-core.js";
export {
  applyMinimaxApiConfig,
  applyMinimaxApiProviderConfig,
  applyMinimaxConfig,
  applyMinimaxHostedConfig,
  applyMinimaxHostedProviderConfig,
  applyMinimaxProviderConfig,
} from "./onboard-auth.config-minimax.js";

export {
  applyOpencodeZenConfig,
  applyOpencodeZenProviderConfig,
} from "./onboard-auth.config-opencode.js";
export {
  CLOUDFLARE_AI_GATEWAY_DEFAULT_MODEL_REF,
  OPENROUTER_DEFAULT_MODEL_REF,
  setAnthropicApiKey,
  setCloudflareAiGatewayConfig,
  setGeminiApiKey,
  setKimiCodingApiKey,
  setMinimaxApiKey,
  setMoonshotApiKey,
  setOpencodeZenApiKey,
  setOpenrouterApiKey,
  setSyntheticApiKey,
  setVeniceApiKey,
  setVercelAiGatewayApiKey,
  setXiaomiApiKey,
  setZaiApiKey,
  writeOAuthCredentials,
  VERCEL_AI_GATEWAY_DEFAULT_MODEL_REF,
  XIAOMI_DEFAULT_MODEL_REF,
  ZAI_DEFAULT_MODEL_REF,
  // 国内模型
  DEEPSEEK_DEFAULT_MODEL_REF,
  setDeepseekApiKey,
  BAIDU_QIANFAN_DEFAULT_MODEL_REF,
  setBaiduQianfanApiKey,
  DOUBAO_DEFAULT_MODEL_REF,
  setDoubaoApiKey,
  TENCENT_HUNYUAN_DEFAULT_MODEL_REF,
  setTencentHunyuanApiKey,
  XINGHUO_DEFAULT_MODEL_REF,
  setXinghuoApiKey,
  SILICONFLOW_DEFAULT_MODEL_REF,
  setSiliconflowApiKey,
  GROQ_DEFAULT_MODEL_REF,
  setGroqApiKey,
  TOGETHER_AI_DEFAULT_MODEL_REF,
  setTogetherAiApiKey,
} from "./onboard-auth.credentials.js";
export {
  buildMinimaxApiModelDefinition,
  buildMinimaxModelDefinition,
  buildMoonshotModelDefinition,
  DEFAULT_MINIMAX_BASE_URL,
  MOONSHOT_CN_BASE_URL,
  KIMI_CODING_MODEL_ID,
  KIMI_CODING_MODEL_REF,
  MINIMAX_API_BASE_URL,
  MINIMAX_HOSTED_MODEL_ID,
  MINIMAX_HOSTED_MODEL_REF,
  MOONSHOT_BASE_URL,
  MOONSHOT_DEFAULT_MODEL_ID,
  MOONSHOT_DEFAULT_MODEL_REF,
} from "./onboard-auth.models.js";
